name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=GUI-Algorithm-Calculator
            -Dsonar.projectName=GUI-Algorithm-Calculator
            -Dsonar.sources=GUI-based-Algorithm-Calculator-master
            -Dsonar.exclusions=**/*.class,**/bin/**
