name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download SonarScanner
        run: |
          curl -sSLo sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-7.2.0.5079-linux-x64.zip
          unzip sonar.zip

      - name: HARD CLEAN PROJECT (IMPORTANT)
        run: |
          find . -name "*.class" -delete || true

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./sonar-scanner-7.2.0.5079-linux-x64/bin/sonar-scanner \
            -Dsonar.projectKey=GUI-Algorithm-Calculator \
            -Dsonar.sources=GUI-based-Algorithm-Calculator-master \
            -Dsonar.exclusions=**/*.class \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.verbose=true
